//
// Created by Doppie on 1/10/2022.
//

#ifndef BULLET_HELL_DEFINITIONS_H
#define BULLET_HELL_DEFINITIONS_H

#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480
#define UNDEFINED_LIST_POINTER nullptr
#define TEXT_LENGTH 128
#define PLAY_AREA_X 360
#define PLAY_AREA_Y 360
#define ADDITIONAL_INFO_X 160
#define ADDITIONAL_INFO_OFFSET 60
#define PLAY_AREA_OFFSET_X 30
#define DISPLAY_AREA_X (PLAY_AREA_OFFSET_X + 1)
#define PLAY_AREA_OFFSET_Y 60
#define DISPLAY_AREA_Y (PLAY_AREA_OFFSET_Y + 1)
#define PLAYER_STARTING_POSITION_X (PLAY_AREA_OFFSET_X + (PLAY_AREA_X / 2))
#define PLAYER_STARTING_POSITION_Y (PLAY_AREA_OFFSET_Y + (PLAY_AREA_Y / 2))
#define DEFAULT_HORIZONTAL_SPEED 0
#define DEFAULT_VERTICAL_SPEED 0
#define UP_SPEED -1
#define DOWN_SPEED 1
#define LEFT_SPEED -1
#define RIGHT_SPEED 1
#define PLAYER_SIZE 8
#define DEFAULT_SPEED_MULTIPLIER 100
#define TOP_OFFSET 1 + (PLAYER_SIZE / 2)
#define BOTTOM_OFFSET (PLAYER_SIZE / 2 + 1)
#define MAX_HEALTH 100
#define MIN_HEALTH 0
#define HEALTHBAR_OFFSET 8
#define ITEM_OFFSET 10
#define SECTION_OFFSET 8
#define HEALTHBAR_SIZE 8
#define HEALTHBAR_SIZE_REDUCTION 1
#define DEFAULT_LEVEL_ID -1
#define DEFAULT_ENEMY_SIZE 16
#define DISPLAY_COMPENSATION 2
#define DISPLAY_POSITION_COMPENSATION 4

class definitions {

};


#endif //BULLET_HELL_DEFINITIONS_H
